name: Deploy Worker
on:
  push:
    branches:
      - main
    paths:
      - 'cloudflare/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install Dependencies
        run: cd cloudflare && npm install
      
      - name: Deploy Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          npm install -g wrangler
          cd cloudflare && wrangler publish